Fix failure to boot app when no pidfile argument is specified
We were blowing up with:

  error: no implicit conversion of nil into String

In the event that the user tried to start the app without passing a
pidfile argument.

This was because we effectively were calling `File.exist?(nil)`.

Change-Id: I0b87563f9048def4e351f007f4163619526d605f
Reviewed-on: https://gerrit.causes.com/27600
Reviewed-by: Noah Silas <noah@causes.com>
Tested-by: Greg Hurrell <greg@causes.com>